### PR TITLE
keybase_daemon_rpc: use KeyFamilyChanged instead of UserChanged

### PR DESCRIPTION
**Pull request by strib**
Issue: KBFS-1238

### CODE REVIEW

**Comment by strib** [comment]
@patrickxb does this look right?  In terms of clearing out cached `keybase1.UserPlusKeys` (and unverified keys) state, `KeyfamilyChanged` should work as a drop-in replacement for `UserChanged`, right?

**Comment by patrickxb** [comment]
Yes, looks right to me.  Will this also trigger a rekey check?

**Comment by strib** [comment]
@patrickxb: Yep, see the whole function here: https://github.com/keybase/kbfs/blob/b62fc0ea9d78c83e824aee864a7b05b8f80d7507/libkbfs/keybase_daemon_rpc.go#L261-L275.

**Comment by patrickxb** [comment]
Great, LGTM.

**Pull request merged**
