### PR TITLE
vendor update keybase/go-framed-msgpack-rpc#117

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by songgao** [comment]
hmm the same test passed on macOS

**Comment by jzila** [comment]
what same test?

**Comment by songgao** [comment]
The CI failed on Windows, on `TestBlockRetrievalWorkerShutdown`. But it passed on my machine with `repeat 10`

**Comment by songgao** [comment]
Oh it's a known flak

**Comment by jzila** [comment]
I think I see the cause

**Pull request merged**
