### PR TITLE
context: Add cleanup function for kbfs socket

### PR DESCRIPTION
**Pull request by jzila**
This first cleans up any existing socket files before trying to bind to it.

I've tested this on my Linux localhost and it works great.

I'd like a review by @oconnor663 and one of the KBFS folks.

### CODE REVIEW

**Comment by oconnor663** [comment]
My plan will be to immediately (like, this afternoon) add in a short-circuit similar to this one: https://github.com/keybase/client/blob/173f21f/go/service/main.go#L721-L725

If that sounds ok to you, this LGTM.

**Comment by jzila** [comment]
That's fine, but I'd guess that it'll never be hit in KBFS.

**Comment by oconnor663** [comment]
That branch is always hit in the systemd configuration we're shooting for. Systemd will provide the listen fd the same way, whether the service is actually started through socket activation, or just with `systemctl start ...`. As long as a `.socket` file exists for the service, systemd will always provide the socket.

I think you're right that we'll probably never sock-activate kbfs. But setting things up this way makes startup a little bit smoother (even though we're robust to it being racy), and it seems to be the way systemd wants it to happen, so I'm running with it :)

**Comment by jzila** [comment]
Sounds good. Please CC me on relevant reviews, I'm interested in following along.

**Comment by songgao** [comment]
With this change, does it mean we are not reusing existing socket file or systemd's socket activation?

**Comment by oconnor663** [comment]
@songgao see https://github.com/keybase/kbfs/pull/1300. In the systemd environment we'll skip this codepath entirely.

**Pull request merged**
