### PR TITLE
Update RPC and AVDL compiler compression support

### PR DESCRIPTION
**Pull request by joshblum**
Revendors `go-framed-msgpack-rpc`  to introduce `CallCompressed` (but without calling it). Depends on ~https://github.com/keybase/node-avdl-compiler/pull/22~, ~https://github.com/keybase/node-avdl-compiler/pull/25~, ~https://github.com/keybase/go-framed-msgpack-rpc/pull/162~, https://github.com/keybase/client/pull/14724

because of the circular CI dependency with client will have to revendor those with master hashes once approved/pass jenkins

- [x] revendor client master
- [x] revendor rpc after: https://github.com/keybase/go-framed-msgpack-rpc/pull/163

### CODE REVIEW

**Comment by joshblum** [comment]
@strib i don't think circle will pass because it clones client and there is a circular dependency. My plan was to merge client, update the kbfs hashes and then merge those so there isn't a breaking point in CI

**Comment by strib** [comment]
@joshblum it doesn't look like the typical circle failure though, probably some flake.  We should make sure it fails in the expected way at least!

**Comment by joshblum** [comment]
ah good point, will try to see why it's timing out

**Comment by akalin-keybase** [comment]
I took a look with josh as to why CircleCI was failing -- it seemed to be hanging on my Linux machine, too. However, building with client set to 14724 works, so I'm inclined to chalk it up to a gomobile bug. Weird.

**Pull request merged**
