### PR TITLE
[KBFS-1293] wait for block deletion in parallel test

### PR DESCRIPTION
**Pull request by songgao**
This should fix https://ci.appveyor.com/project/keybase/kbfs/build/1.0.4659

### CODE REVIEW

**Comment by strib** [comment]
@songgao the test shutdown method already waits on SyncFromServer for each user, before running the consistency checks, so I don't think this will fix the issue.

**Comment by strib** [comment]
Oh crap I bet it needs to be added here: https://github.com/keybase/kbfs/blob/master/libkbfs/config_local.go#L707

That's where we make sure all users have finished archiving before we turn off the block server.  Because by the time we call config.Shutdown for the second user, the block server could already be shut down.  D'oh!  Sorry for not catching this before.

**Comment by songgao** [comment]
Ah that make sense! Thanks @strib!

**Comment by songgao** [comment]
@strib Here it is. I also made sure `waitForDeletingBlocks` is called whenever `waitForArchives` is called

**Comment by strib** [comment]
Looks good to me, thanks!

**Pull request merged**
