### PR TITLE
Add missing libkb file

### PR DESCRIPTION
**Pull request by joshblum**
this file was missing in the vendor package

### CODE REVIEW

**Comment by strib** [comment]
Why isn't vendor.json updated with a new checksum?

**Comment by joshblum** [comment]
these files are git ignored, the correct checksum was put into https://github.com/keybase/kbfs/pull/1789 but this file was mistakenly missing from the merge

**Comment by strib** [comment]
I'm confused, `msgpack.go` is being gitignored?

**Comment by joshblum** [comment]
```
$ git add vendor/github.com/keybase/client/go/libkb
The following paths are ignored by one of your .gitignore files:
vendor/github.com/keybase/client/go/libkb
Use -f if you really want to add them.
```

although i can't find any `.gitignore`s in this repo or my global config that are causing this, i'm not sure the root cause

**Comment by joshblum** [comment]
but we should get this in since it breaks CI for all

**Comment by strib** [comment]
I'd guess the root cause is that this is a brand new file that got added to master while your client PR was in review, and when you squashed yours in and re-merged, you didn't `git add --all vendor` in kbfs afterwards.

No idea about the gitignore thing.

Let me try it locally.

**Comment by joshblum** [comment]
yeah i didn't realize that the gitignore was in play and that i should be force adding those vendor dirs

**Comment by strib** [comment]
Hmm you're right.  I don't get the gitignore error, but `govendor` doesn't update the checksum when I re-vendor it, so something's weird with your local gitignore config.

**Comment by joshblum** [comment]
sorry about that! i'll try to figure out what is setting it locally so it doesn't happen again

**Pull request merged**
