### PR TITLE
Use in-memory server for libkbfs tests in Jenkins

### PR DESCRIPTION
**Pull request by akalin-keybase**

### CODE REVIEW

**Comment by jzila** [comment]
This is redundant. The variables are already set here: https://github.com/keybase/kbfs/blob/f59e112f9ba55569022435ccb7dfb59c104445b8/Jenkinsfile#L178-L181

**Comment by jzila** [comment]
It seems like what you want is to move the `withEnv` call into the `mdserver` and `bserver` sections.

**Comment by jzila** [comment]
Alternatively, you can override the `withEnv` with another one inside `libkbfs`

**Comment by akalin-keybase** [comment]
Ah, didn't notice that. PTAL!

**Comment by jzila** [comment]
You also have to remove the `withEnv` command at the beginning of the function, otherwise there's no difference.

**Comment by akalin-keybase** [comment]
D'oh! Try now. :) (Also rebased on master.)

**Comment by jzila** [comment]
LGTM

**Pull request merged**
