### PR TITLE
Revendor keybase/client after externals refactor

### PR DESCRIPTION
**Pull request by maxtaco**
- change libkb -> externals for NormalizeSocialAssertion and friends

### CODE REVIEW

**Comment by maxtaco** [comment]
Sorry this merge is so big.....

**Comment by akalin-keybase** [comment]
:+1:

**Comment by maxtaco** [comment]
Do I do the same to `kbfs-server` next?

**Comment by akalin-keybase** [comment]
Yeah, may as well. You'd vendor both kbfs and client/go. I don't think anything in server calls these functions directly, but worth checking!

**Comment by maxtaco** [comment]
I think I saw that MDServer does...

**Comment by maxtaco** [comment]
There's this one guy:

```
mdserver//dynamodb_storage.go:1164:		assertion, ok := libkb.NormalizeSocialAssertion(attrAssertion.Value)
```

My recompile after revendoring libkbfs failed, maybe it's not ready for a revendor yet:

```
# github.com/keybase/kbfs-server/mdserver
mdserver/account_reset_manager.go:269: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:270: head.md.MD.Revision undefined (type libkbfs.MutableBareRootMetadata has no field or method Revision)
mdserver/account_reset_manager.go:312: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:317: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:325: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:354: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:374: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:379: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:392: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:397: head.md.MD.ID undefined (type libkbfs.MutableBareRootMetadata has no field or method ID)
mdserver/account_reset_manager.go:397: too many errors
```

**Comment by akalin-keybase** [comment]
ah, crap, yeah, @aalness, looks like you need to vendor kbfs-server for your MD refactor? We'll take care of it, @maxtaco!

**Comment by maxtaco** [comment]
No worries.  There's only one change I think I had to make:  https://github.com/keybase/kbfs-server/pull/98/commits/380c8dbe4d22fcbc97e2d03a0b49dcc49163a9c6

**Pull request merged**
