### PR TITLE
key_manager: mark rekey identifies with the KBFS_REKEY behavior

### PR DESCRIPTION
**Pull request by strib**
This lets the service suppress popups unless something is wrong.

Issue: KBFS-1928

### CODE REVIEW

**Comment by maxtaco** [comment]
Thanks.  I think we're going to be suppressing tracker popups in all cases, even if there is an error. I think the issue is that it's just too confusing otherwise.

CC: @malgorithms  on what's best here.

**Comment by strib** [comment]
cc: @maxtaco: do I need to wait until the client-side support for this identify behavior is ready, or will the client continue to perform the default behavior if it doesn't recognize the behavior?

**Comment by strib** [comment]
> Thanks. I think we're going to be suppressing tracker popups in all cases, even if there is an error

Wow, that seems super duper dangerous.  Rekey is a pretty sensitive operation.

cc: @malgorithms

**Comment by strib** [comment]
@maxtaco: oh maybe you mean the rekey will still fail, there just won't be a popup?

**Comment by jzila** [comment]
Maybe instead of tracker popups, we should be introducing a tracker notification pane on the main app, along with high priority un-toggleable toasts.

**Comment by maxtaco** [comment]
I meant the identify will fail, which will block the rekey, but the user won't know. 

Asking @oconnor663 what happens when we get a new enum we don't know.  I think we're ok.

**Comment by maxtaco** [comment]
@jzila yes that's the plan on the "people tab" when we get around to it.

**Comment by strib** [comment]
@maxtaco: thanks make sense!  I misinterpreted.

**Comment by maxtaco** [comment]
@strib, yes....  presumably we can just return an error to `Identify2` but suppress all UI, and it hits all of the requirements?

**Comment by oconnor663** [comment]
Here are the important functions for the identify behaviors: https://github.com/keybase/client/blob/master/go/protocol/keybase1/extras.go#L751-L764

The WarningInsteadOfErrorOnBrokenTracks function in particular is conservative, and it won't suppress errors for a new behavior that it doesn't recognize.

**Comment by maxtaco** [comment]
@songgao yeah @oconnor663 is on it!

**Comment by maxtaco** [comment]
Nice work here by @oconnor663 to make this addition so easy on the Core side btw...

**Comment by oconnor663** [comment]
Pretty sure I was just following @songgao's pattern :)

**Pull request merged**
