### PR TITLE
cr: don't bother resolving paths that were deleted on both sides

### PR DESCRIPTION
**Pull request by strib**
This is part 1 of the fix for KBFS-1202.

Issue: KBFS-1202

### CODE REVIEW

**Comment by strib** [comment]
That Windows failure is weird since it passed on the other platforms.  Looking into it.

**Comment by strib** [comment]
Ah it's because Windows turns `setex` into `setmtime`, and that has issues apparently.  Looking into it.

**Comment by strib** [comment]
Ok fixed now, ready for a look.

**Comment by akalin-keybase** [comment]
lgtm

**Pull request merged**
