### PR TITLE
Update Appveyor to go 1.9

### PR DESCRIPTION
**Pull request by akalin-keybase**
Also fix resulting test failures.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
@taruti any idea why TestStatAlias now fails, i.e. a different mode is returned for an alias? Should I change the expectation?

**Comment by taruti** [comment]
I think they changed how things work in the Go stdlib, which affects our tests. I'll dig it up.

**Comment by taruti** [comment]
https://github.com/golang/go/commit/1989921aef60c83e6f9127a8448fb5ede10e9acc is the culprit.

Can be fixed with:
```
diff --git a/libdokan/mount_test.go b/libdokan/mount_test.go
index 91079f1d..02faaac7 100644
--- a/libdokan/mount_test.go
+++ b/libdokan/mount_test.go
@@ -242,7 +242,7 @@ func TestStatAlias(t *testing.T) {
        if err != nil {
                t.Fatal(err)
        }
-       if g, e := fi.Mode().String(), `dLrwxrwxrwx`; g != e {
+       if g, e := fi.Mode().String(), `Lrw-rw-rw-`; g != e {
                t.Errorf("wrong mode for alias : %q != %q", g, e)
        }
        // TODO Readlink support.
```

**Comment by akalin-keybase** [comment]
Thanks @taruti! Fixed.

**Comment by akalin-keybase** [comment]
Ready for review!

**Pull request merged**
