### PR TITLE
[KBFS-1516] Move MDServerError types into kbfsmd package

### PR DESCRIPTION
**Pull request by akalin-keybase**
This removes another server dependency on libkbfs.

Also rename to kbfsmd.ServerError*.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
This is 99% automated renaming.

**Comment by akalin-keybase** [comment]
I thought about that, and didn't have a strong opinion about. @strib what do you think? `tlfmd` package perhaps, or `kbfsmd`? (`md` seems too short of a name)

**Comment by strib** [comment]
`kbfsmd` works for me.  Also not a very strong opinion though.

**Comment by jzila** [comment]
+1 to `kbfsmd`

**Comment by akalin-keybase** [comment]
Okay, cool. I'll rework this PR (and its dependencies) to use `kbfsmd`. Stay tuned!

**Comment by akalin-keybase** [comment]
Okay, now all of these are in `kbfsmd`. PTAL!

**Pull request merged**
