### PR TITLE
Update protocol usage after protocol package rename

### PR DESCRIPTION
**Pull request by gabriel**
Did a rename in go files for protocol to protocol/keybase1.

Re-vendoring client (update protocol to protocol/keybase1), ran the following:
```
govendor remove github.com/keybase/client/go/protocol
govendor add github.com/keybase/client/go/protocol/keybase1

govendor update github.com/keybase/client/go/auth
govendor update github.com/keybase/client/go/externals
govendor update github.com/keybase/client/go/kex2
govendor update github.com/keybase/client/go/libkb
govendor update github.com/keybase/client/go/logger
```

### CODE REVIEW

**Comment by gabriel** [comment]
Mobile fails when client and kbfs are out of sync. This puts them back in sync.
@mmaxim @maxtaco

**Comment by gabriel** [comment]
cc @akalin-keybase

**Comment by maxtaco** [comment]
👍 for me, but looks like a CI failure.

**Comment by akalin-keybase** [comment]
:+1:

**Comment by mmaxim** [comment]
👍

**Comment by akalin-keybase** [comment]
```
vendor/github.com/keybase/client/go/libkb/identify_outcome.go:13:2: cannot find package "github.com/keybase/client/go/gregor" in any of:
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/gregor (vendor tree)
	/home/jenkins/.gvm/gos/go1.7/src/github.com/keybase/client/go/gregor (from $GOROOT)
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/client/go/gregor (from $GOPATH)
```

**Comment by akalin-keybase** [comment]
Oh, there are a couple more packages that need adding, I think: https://ci.keybase.io/job/kbfs/job/PR-279/1/execution/node/108/log/

```
vendor/github.com/keybase/client/go/protocol/keybase1/chat_local.go:7:2: cannot find package "github.com/keybase/client/go/protocol/chat1" in any of:
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/chat1 (vendor tree)
	/home/jenkins/.gvm/gos/go1.7/src/github.com/keybase/client/go/protocol/chat1 (from $GOROOT)
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/client/go/protocol/chat1 (from $GOPATH)
vendor/github.com/keybase/client/go/protocol/keybase1/gregor.go:7:2: cannot find package "github.com/keybase/client/go/protocol/gregor1" in any of:
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/gregor1 (vendor tree)
	/home/jenkins/.gvm/gos/go1.7/src/github.com/keybase/client/go/protocol/gregor1 (from $GOROOT)
	/tmp/jenkins-c1551c7e/workspace/kbfs/PR-279/go/src/github.com/keybase/client/go/protocol/gregor1 (from $GOPATH)
```

**Pull request merged**
