### PR TITLE
stderrutils: build on android

### PR DESCRIPTION
**Pull request by philips**
Tested on Android Termux. I don't know why this was like this before.

```
$ go env | grep GOOS
GOOS="android"
$ git push origin master
Initializing Keybase... done.
Syncing with Keybase... done.
Counting and decrypting: 3 objects... done.
Preparing and encrypting: (100.00%) 3/3 objects... done.
Indexing hashes: (100.00%) 3/3 objects... done.
Indexing CRCs: (100.00%) 3/3 objects... done.
Indexing offsets: (100.00%) 3/3 objects... done.
Syncing encrypted data to Keybase: (100.00%) 7.45/7.45 KB... done.
To keybase://private/philips/foo
   6c3a499..b226459  master -> master
```

### CODE REVIEW

**Comment by philips** [comment]
cc @songgao @strib

**Comment by philips** [comment]
If we get this merged and cut a release I can bump the termux package and close out #1231

**Comment by strib** [comment]
Looks good to me, but would you mind just completely removing `dup_stderr_dummy.go` since it's unused after this change?  Then I'll merge.  Thanks!

**Comment by philips** [comment]
@songgao done, removed dummy file. Tested and it works.

**Comment by songgao** [comment]
Thanks @philips !

**Comment by strib** [comment]
Passed full CI on #1778.

**Pull request merged**
