### PR TITLE
small fix to set success flag in kbgit test

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by songgao** [comment]
I was confused too ... perhaps journal maintained a file descriptor that it kept writing into and kernel kept it alive until closed?

**Comment by strib** [comment]
No, it makes directory entries.  But it might just call something like "mkdir -p" whenever it makes a new entry.

**Comment by songgao** [comment]
Oh OK that makes sense. Does it mean we don't actually need to create the tempdir manually in tests?

**Comment by strib** [comment]
Maybe but let's not mess with it now.  Did you actually see a test fail without this fix, or just something you noticed?

**Comment by songgao** [comment]
Sounds good. (No tests failing because of this; I was setting up tests for locking and noticed this.)

**Pull request merged**
