### PR TITLE
kbfscrypto: core.keybase.io uses the API root CA cert

### PR DESCRIPTION
**Pull request by strib**

### CODE REVIEW

**Comment by songgao** [comment]
Thanks for working it out!

**Comment by strib** [comment]
I should mention I tested it using `openssl s_client -CAfile XXX -connect XXX` from ctl.kbfs, and verified that the old cert failed while the new one worked.

**Comment by strib** [comment]
> Could you add a comment explaining the cert situation?

What should the comment say that is not already clear from the code?

**Comment by songgao** [comment]
(talked offline; no need for comment)

**Pull request merged**
