### PR TITLE
md_util: decrypt the private MD into a copy after it's cached

### PR DESCRIPTION
**Pull request by strib**
Otherwise, we can have a race with multiple goroutines trying to decrypt into the same MD concurrently.

Issue: KBFS-1161

### CODE REVIEW

**Comment by akalin-keybase** [comment]
This fixes the race, but I think the locking belongs in a better place than inside RootMetadata. My read of the problem is that `getMDRange` puts all MDs fetched from the server in the md cache, even if they're not decryptable. Then multiple things may race in `getMergedMDUpdates` in decrypting the same MD object.

I think a better solution would be:

1) Don't cache undecryptable MDs in `getMDRange`;
2) Instead cache them in `getMergedMDUpdates` after they're decrypted;
3) For good measure, check that all MDs in `getUnmergedMDUpdates` are already decrypted.

Then we then just rely on the MD cache's synchronization. What do you think?

**Comment by strib** [comment]
I thought about that, but it's much more wasteful on the performance axis, and causes more load on the server, since the same MDs are more likely to be fetched multiple times from the same client over the network.  We'd effectively be increasing the window between the fetch and the caching, where another fetch can come in and consume resources redundantly.  Plus, for things that we can't decrypt yet, due to rekeys not happening yet, we're increasing that window a lot.

What specifically concerns you about the PR?  I don't really understand why it's bad -- it's introducing locking at the exact point of contention.

**Comment by akalin-keybase** [comment]
My problem with this PR is that it makes it difficult to reason about RootMetadata without knowing about the details about this particular race. For example, someone new (or me in 6 months) might ask why it's okay to write through the `Data()` pointer in FBO, or why can't anything be reading through the `Data()` pointer at the same time `setData()` is happening, and to answer those questions one would need to know a lot about how FBO and md_util and md_cache interact.

Another way to say my problem with this PR is that I think that synchronization should happen at the level that needs it; in this case, the race is between operations on the md cache, so it should be the md cache that does the synchronization (roughly).

How about this solution: in `getMergedMDUpdates`, make a copy of `rmd` and use that when calling `decryptMDPrivateData`. Then put that in the MD cache, and replace the entry in `mergedRmds`. Then we wouldn't be fetching the same MD multiple times, but we might do extra copies and be decrypting multiple times. I think that's fine, though, as the case where we do the copy isn't very common, and the race (mostly?) happens for testing, and so decrypting multiple times is okay in that case. What do you think?

**Comment by strib** [comment]
That seems reasonable, and I'll try it out later today when I get some time.

Though I don't really agree that the cache is where the synchronization is needed -- the race is on setting a field on an individual field in a particular object that could be referenced in lots of different places, not just the cache.  In this case, it happens to be related to the cache, but I could imagine other scenarios when the data is kept elsewhere (say as the `head` in `folderBranchOps`) and later decrypted.  Under this proposal, we have to remember to copy it every time we call `decryptMDPrivateData` if there might be other references out there somewhere (the cache being one possible location among many).

**Comment by akalin-keybase** [comment]
Hmm...do you think there'll be other cases where we have to decrypt the data field? My conception (which could be wrong) is that in the good old days, whenever we got an MD from the server, we'd just decrypt it immediately and stick it in the cache. Now, we might not be able to decrypt it immediately, but if we see the whole range we can decrypt it before FBO sees it, and if we can't decrypt it that's an error. If you think that someday an FBO would e.g. have a `head` that isn't decryptable, then that would change things...

**Comment by strib** [comment]
No, I don't have a specific use case in mind.  Although, now that I'm looking around, we do already call `decryptMDPrivateData` from `KeyManagerStandard.Rekey()`, so I'd have to think about how that's affected by this new scheme.

**Comment by strib** [comment]
@akalin-keybase: does my previous comment (that we already call `decryptMDPrivateData` from other places) sway you at all?  Or do you still think it's a good idea to have the locking center around the cache?

**Comment by akalin-keybase** [comment]
I think it's still a good idea to have the locking center around the cache. Looking at `Rekey()`, its argument is already assumed to be modifiable without any locking, and so i think the bare `decryptMDPrivateData` call there is fine.

Other than the existing calls, I can't foresee any other cases where we'd call `decryptMDPrivateData`, so I think if they come up we can figure out if it's still best to do the locking around the cache then.

**Comment by strib** [comment]
I don't follow why `Rekey()` can assume the private MD is modifiable without locking.  Yes, only one goroutine can call `Rekey()` at a time because of locking in FBO, but why couldn't `getMergedMDUpdates()` be called by another goroutine at the same time, and end up running concurrently with the `decryptMDPrivateData()` call in `Rekey()` (after a paper key is entered at a prompt, for example)?

**Comment by akalin-keybase** [comment]
It's not the FBO locking, but the fact that `FBO.rekeyLocked` calls `getMDForRekeyWriteLocked` ( https://github.com/keybase/kbfs/blob/master/libkbfs/folder_branch_ops.go#L3604 ), which calls `md.MakeSuccessor`, and that is what is passed to `decryptMDPrivateData`.

**Comment by strib** [comment]
Ah right, I forgot Rekey worked with a copy.  Thanks, will look into changing this on Monday.

**Comment by strib** [comment]
Ok @akalin-keybase, ready for another look.

**Comment by akalin-keybase** [comment]
lgtm

**Pull request merged**
