### PR TITLE
[KBFS-1396] Associate journal block ops with an MD revision

### PR DESCRIPTION
**Pull request by akalin-keybase**
Previously, we would just flush all known block ops before
all known MD ops, which isn't optimal. Now we tag block
ops with the MD revision number, and then flush all block
ops before the earliest revision number in the MD journal,
then flush that MD, and repeat.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Note that this is based on top of https://github.com/keybase/kbfs/pull/285 .

**Comment by akalin-keybase** [comment]
This is now on top of master.

**Comment by akalin-keybase** [comment]
Hmm, I found a problem with this PR. It assumes that MD revisions never decrease, but that's not true, since if you're on a branch and conflict resolution happens, then the next MD revision will be 1 + the merged revision, which can be less than the branch's head revision. This manifests as block ops being "stuck" in the journal and not flushed for a while.

Don't review yet while I rework this!

**Comment by strib** [comment]
@akalin-keybase: in sprint you asked me if I'd looked into this yet, but your last comment says not to.  Is it ready for review now?

**Comment by akalin-keybase** [comment]
@strib not yet. I think I was confused in sprint. Let me get it up to date first...

**Comment by akalin-keybase** [comment]
This PR is superseded by https://github.com/keybase/kbfs/pull/329

**Pull request closed without merging**
