### PR TITLE
crypto_client: save correct signature type when signing for KBFS

### PR DESCRIPTION
**Pull request by aalness**

### CODE REVIEW

**Comment by aalness** [comment]
The server rejects the metadata block as having an invalid signature. I think the only good test for it will be with kbfsdocker since that's the only time we actually use the real client.

**Comment by strib** [comment]
Cool.  Seems like our in-memory servers should do those same checks, so this would be caught in our `kbfs` repo tests.  But no need to do that before merging this.

**Comment by aalness** [comment]
Those would use `CrytpoLocal` though which doesn't have the bug.

**Comment by strib** [comment]
Ahhh makes sense.  Thanks.

**Pull request merged**
