### PR TITLE
cr: fix block unref issue for multi-sync CR, and add test

### PR DESCRIPTION
**Pull request by strib**
Issue: KBFS-1562

### CODE REVIEW

**Comment by strib** [comment]
The Jenkins failure seems to be a CI network flake or something.

The Appveyor failure is more concerning, but I can't repro on Linux after 1000+ runs.  I don't think it's related to this PR but I will run it again before I merge this.

**Comment by strib** [comment]
Looks like a user hit this in the wild already, which resulted in data loss.  I'm going to push it -- @akalin-keybase I will fix any comments in a separate PR.

**Comment by strib** [comment]
Actually I take it back, the issue hadn't made it into production yet, even on Linux.  Sorry!

**Comment by akalin-keybase** [comment]
lgtm

**Pull request merged**
