### PR TITLE
Vendor client

### PR DESCRIPTION
**Pull request by akalin-keybase**
Also vendor go-winio and go-jsonw.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
This is the kbfs side of https://github.com/keybase/client/pull/13514/files -- once everything is approved and that is landed, I'll update the vendor hashes on this PR and merge it.

**Comment by akalin-keybase** [comment]
Ping! Note that the circleci failure is expected -- the other two should pass now.

**Comment by songgao** [comment]
Ah! Just realized you are already doing vendoring here. I'll rebase after this is in then!

**Comment by akalin-keybase** [comment]
CircleCI passes, so merging (previous runs had Jenkins / Appveyor pass)

**Pull request merged**
