### PR TITLE
moving admin list from libkbfs to libkb

### PR DESCRIPTION
**Pull request by songgao**
will update commit sha1 once https://github.com/keybase/client/pull/9492 is merged.

### CODE REVIEW

**Comment by songgao** [comment]
did I not? ugh

**Comment by songgao** [comment]
do we still want that TODO?

> TODO: Add a server endpoint to get this data.

**Comment by songgao** [comment]
The API server's storage doesn't include Taru and Michal though :)

**Comment by jzila** [comment]
True. I guess having them decoupled is good.

**Comment by songgao** [comment]
(I'll postpond the merge until after https://github.com/keybase/client/pull/9493)

**Pull request merged**
