### PR TITLE
Dokan 1.2 and amd64 CI

### PR DESCRIPTION
**Pull request by taruti**
Appveyor passes, but let us wait with merging till everything is clear.

### CODE REVIEW

**Comment by zanderz** [comment]
PS: is jenkins a problem? I can't tell.

**Comment by taruti** [comment]
@zanderz Jenkins passed in the end. Can we merge this in - now that the 64 bit stuff is merged?

**Comment by zanderz** [comment]
What version do we want to consider old after this?

**Comment by zanderz** [comment]
OK with me as long as I can get a thumb soon on https://github.com/keybase/client/pull/13922

**Pull request merged**
