### PR TITLE
Push KBFS to docker hub if triggered by client master

### PR DESCRIPTION
**Pull request by jzila**
r? @songgao

### CODE REVIEW

**Comment by jzila** [comment]
@songgao 1. is incorrect, 2. is correct. We can make 1. true, but it'll slow down client builds by a lot (because it won't start KBFS tests until client tests have passed)

**Comment by songgao** [comment]
@jzila that makes sense. But doesn't this make it possible to push a kbfs image with broken client?

**Comment by jzila** [comment]
Yes

**Comment by songgao** [comment]
Got you; we'll just need to watch out master builds then :)

**Pull request merged**
